"""Deterministic allowlist-only widget bundle, manifest and archive validation. No secrets."""
import json
import re
import struct
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LOGOS = {'logo_main.png': (400, 272), 'logo_small.png': (108, 108),
         'logo.png': (130, 100), 'logo_medium.png': (240, 84), 'logo_min.png': (84, 84)}
FILES = ['manifest.json', 'script.js', 'style.css', 'i18n/ru.json'] + ['images/' + n for n in LOGOS]


def validate():
    manifest = json.loads((ROOT / 'manifest.json').read_text(encoding='utf-8'))
    lang = json.loads((ROOT / 'i18n/ru.json').read_text(encoding='utf-8'))
    widget = manifest['widget']
    assert widget['interface_version'] == 2 and widget['init_once'] is False
    assert widget['locale'] == ['ru'] and widget['installation'] is True
    assert re.fullmatch(r'\d+\.\d+\.\d+', widget['version'])
    assert widget['support']['link'].startswith('https://')
    assert manifest['locations'] == ['lcard-1', 'settings']
    assert manifest['tour']['is_tour'] is False
    for key in ['name', 'description', 'short_description']:
        group, name = widget[key].split('.')
        assert lang[group][name]
    group, name = manifest['tour']['tour_description'].split('.')
    assert lang[group][name]
    assert set(manifest['settings']) == {'contact_id_field', 'channel_field', 'referral_enum'}
    for setting in manifest['settings'].values():
        group, name = setting['name'].split('.')
        assert lang[group][name] and setting['type'] == 'text' and setting['required'] is False
    for name, size in LOGOS.items():
        data = (ROOT / 'images' / name).read_bytes()
        assert data[:8] == b'\x89PNG\r\n\x1a\n' and len(data) < 300 * 1024
        assert struct.unpack('>II', data[16:24]) == size
    for name in FILES:
        data = (ROOT / name).read_bytes()
        assert not data.startswith(b'\xef\xbb\xbf'), name
        if not name.endswith('.png'):
            text = data.decode('utf-8')
            assert not re.search(r'(?i)(Bearer\s+[a-z0-9_.-]+|-----BEGIN .*PRIVATE KEY|eyJ[a-zA-Z0-9_-]{30,}\.)', text), name
    return widget['version']


def build():
    source = '\n'.join((ROOT / 'src' / name).read_text(encoding='utf-8')
                       for name in ['core.js', 'api.js', 'card.js', 'widget.js'])
    bundle = "// Generated by build.py; edit src/ instead.\ndefine(['jquery'], function ($) {\n" + source + '\nreturn ReferrerWidget;\n});\n'
    (ROOT / 'script.js').write_text(bundle, encoding='utf-8')
    version = validate()
    output = ROOT / 'dist' / ('referrer-' + version + '.zip')
    output.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name in FILES:
            info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o100644 << 16
            archive.writestr(info, (ROOT / name).read_bytes())
    with zipfile.ZipFile(output) as archive:
        assert sorted(archive.namelist()) == sorted(FILES)
        assert archive.testzip() is None
        assert json.loads(archive.read('manifest.json'))['widget']['version'] == version
    print('Validated manifest, logo sizes, UTF-8 and archive allowlist:', output)
    return output


if __name__ == '__main__':
    build()
