// Generated by build.py; edit src/ instead.
define(['jquery'], function ($) {
'use strict';
function createReferrerCore() {
  const ID_NAME = 'Рекомендовал – Contact ID';
  const CHANNEL_NAME = 'Канал привлечения';
  const normalize = value => String(value || '').trim().replace(/[‐‑‒–—−]/g, '-').replace(/\s+/g, ' ').toLowerCase();
  function id(value) {
    const text = String(value == null ? '' : value).trim();
    if (!/^[1-9]\d*$/.test(text) || !Number.isSafeInteger(Number(text))) return null;
    return Number(text);
  }
  function field(fields, name, configured, optional) {
    const matches = fields.filter(item => normalize(item.name) === normalize(name));
    if (configured) {
      const found = matches.find(item => item.id === id(configured));
      if (!found) throw new Error('Проверьте ID поля «' + name + '» в настройках виджета.');
      return found;
    }
    if (matches.length > 1) throw new Error('Несколько полей «' + name + '». Укажите нужный ID в настройках.');
    if (!matches.length && !optional) throw new Error('Нет поля «' + name + '». Настройте его по README; виджет поля не создаёт.');
    return matches[0] || null;
  }
  function resolve(fields, settings) {
    const referrer = field(fields, ID_NAME, settings.contact_id_field, false);
    if (!['numeric', 'text'].includes(referrer.type) || referrer.is_api_only) {
      throw new Error('Поле Contact ID должно быть доступным в карточке числом или текстом.');
    }
    const channel = field(fields, CHANNEL_NAME, settings.channel_field, true);
    let referral = null;
    if (channel) {
      if (channel.type !== 'select') throw new Error('Канал привлечения должен быть полем «Список».');
      const enums = channel.enums || [];
      const matches = settings.referral_enum
        ? enums.filter(item => item.id === id(settings.referral_enum))
        : enums.filter(item => ['рекомендация', 'рекомендации'].includes(normalize(item.value)));
      if (matches.length !== 1) throw new Error('Укажите ID значения рекомендации в настройках виджета.');
      referral = matches[0];
    }
    return {referrer, channel, referral};
  }
  function value(record, fieldId) {
    const found = (record.custom_fields_values || []).find(item => item.field_id === fieldId);
    return found && found.values && found.values[0] || null;
  }
  function savedId(record, fieldId) {
    const entry = value(record, fieldId);
    if (!entry || entry.value === '' || entry.value == null) return null;
    const parsed = id(entry.value);
    if (!parsed) throw new Error('В поле Contact ID записано некорректное значение. Исправьте его вручную.');
    return parsed;
  }
  function eligible(record, schema) {
    if (!schema.channel) return true;
    const entry = value(record, schema.channel.id);
    return !!entry && (id(entry.enum_id) === schema.referral.id ||
      (!entry.enum_id && entry.value === schema.referral.value));
  }
  function payload(leadId, contactId, schema) {
    if (!id(leadId) || !id(contactId)) throw new Error('Некорректный ID сделки или контакта.');
    return [{id: id(leadId), custom_fields_values: [{field_id: schema.referrer.id,
      values: [{value: schema.referrer.type === 'numeric' ? id(contactId) : String(id(contactId))}]}]}];
  }
  function phone(contact) {
    const field = (contact.custom_fields_values || []).find(item => item.field_code === 'PHONE');
    return field && field.values && field.values.map(item => String(item.value || '')).filter(Boolean).join(', ') || '';
  }
  function errorMessage(error) {
    if (error.status === 401) return 'Сессия истекла. Обновите страницу и войдите в amoCRM.';
    if (error.status === 403) return 'Недостаточно прав для этой операции.';
    if (error.status === 404) return 'Запись удалена или недоступна.';
    if (error.status === 429) return 'Лимит запросов. Подождите и повторите поиск.';
    if (error.status) return 'Ошибка API (' + error.status + '). Повторите чтение; запись автоматически не повторяется.';
    return error.message || 'Ошибка сети. Проверьте результат перед повторной записью.';
  }
  return {id, normalize, resolve, savedId, eligible, payload, phone, errorMessage};
}
if (typeof module === 'object' && module.exports) module.exports = createReferrerCore;

'use strict';
function createReferrerApi(ajax, wait) {
  const sleep = wait || (ms => new Promise(resolve => setTimeout(resolve, ms)));
  let tail = Promise.resolve();
  let stopped = false;
  const companies = new Map();
  function request(method, path, body, valid) {
    if (!/^\/api\/v4\/(contacts(?:\/[1-9]\d*)?|companies\/[1-9]\d*|leads(?:\/[1-9]\d*|\/custom_fields)?)(?:\?[^#]*)?$/.test(path) ||
        !['GET', 'PATCH'].includes(method) || (method === 'PATCH' && path !== '/api/v4/leads')) {
      return Promise.reject(new Error('Недопустимый запрос виджета.'));
    }
    const run = async () => {
      if (stopped || (valid && !valid())) throw new Error('Запрос отменён: карточка или выбор изменились.');
      let response;
      try {
        response = await ajax({url: path, method, dataType: 'json', timeout: 15000,
          ...(body ? {contentType: 'application/json', data: JSON.stringify(body)} : {})});
      } finally {
        // One sequential queue per widget instance, including failures. No blind write retries.
        await sleep(300);
      }
      return response || {};
    };
    const task = tail.then(run);
    tail = task.catch(() => {});
    return task;
  }
  async function fields() {
    const result = [];
    for (let page = 1; page <= 100; page++) {
      const data = await request('GET', '/api/v4/leads/custom_fields?page=' + page + '&limit=50');
      result.push(...((data._embedded || {}).custom_fields || []));
      if (!(data._links || {}).next) return result;
    }
    throw new Error('Список полей неполный. Настройка остановлена.');
  }
  async function companyName(company) {
    if (!company || !/^[1-9]\d*$/.test(String(company.id))) return '';
    if (company.name) return company.name;
    if (!companies.has(company.id)) {
      companies.set(company.id, request('GET', '/api/v4/companies/' + company.id)
        .then(data => data.name || '').catch(error => { companies.delete(company.id); throw error; }));
    }
    return companies.get(company.id);
  }
  return {request, fields, companyName, stop() { stopped = true; }};
}
if (typeof module === 'object' && module.exports) module.exports = createReferrerApi;

'use strict';
// Keep the small native-form adapter separate: DOM names are not a stable API contract.
// Fail closed if amoCRM changes its field markup. Never guess a different input.
function createReferrerCard($, app, fieldId) {
  const card = app.data && app.data.current_card;
  if (!card || !card.model) throw new Error('Откройте сохранённую карточку сделки.');
  const leadId = Number(card.id);
  function current() { return app.data && app.data.current_card === card && Number(card.id) === leadId; }
  function input(selectedFieldId, writable) {
    selectedFieldId = selectedFieldId || fieldId;
    const prefix = 'CFV[' + selectedFieldId + ']';
    const matches = $('input').filter(function () {
      const name = this.getAttribute('name') || '';
      return name === prefix || name === prefix + '[VALUE]' ||
        new RegExp('^CFV\\[' + selectedFieldId + '\\]\\[\\d+\\]\\[VALUE\\]$').test(name);
    });
    if (matches.length !== 1 || (writable && (matches.prop('disabled') || matches.prop('readOnly')))) {
      throw new Error('Поле Contact ID недоступно для редактирования в карточке. Откройте вкладку с этим полем и нажмите «Обновить».');
    }
    return matches;
  }
  return {
    id: leadId, current,
    raw(selectedFieldId) { return String(input(selectedFieldId, !selectedFieldId).val() || '').trim(); },
    sync(expected, value) {
      if (!current()) return false;
      const target = input(null, true);
      if (String(target.val() || '').trim() !== expected) return false;
      target.val(String(value)).trigger('input').trigger('change');
      return String(target.val() || '').trim() === String(value);
    },
    onChange(handler) { card.model.on('change', handler); },
    offChange(handler) { card.model.off('change', handler); }
  };
}
if (typeof module === 'object' && module.exports) module.exports = createReferrerCard;

'use strict';
function ReferrerWidget() {
  const self = this;
  const core = createReferrerCore();
  let state = null;
  function destroy() {
    if (state) {
      state.dead = true;
      state.seq++;
      clearTimeout(state.timer);
      state.api.stop();
      if (state.card) state.card.offChange(state.onChange);
      state.root.off('.referrer').remove();
      state = null;
    }
  }
  function mount() {
    destroy();
    const app = window.APP;
    if (!app || !app.isCard() || app.getBaseEntity() !== 'leads') return true;
    self.render_template({caption: {class_name: 'personal-referrer-caption', html: 'Рекомендатель'},
      body: '', render: '<div class="personal-referrer"></div>'});
    const root = $('.personal-referrer').last();
    const cssId = 'personal-referrer-css';
    if (!document.getElementById(cssId)) {
      $('<link>', {id: cssId, rel: 'stylesheet', href: self.params.path + '/style.css?v=' + self.get_version()}).appendTo('head');
    }
    const searchId = 'personal-referrer-search';
    root.append($('<label>', {for: searchId, text: 'Рекомендатель'}));
    const selected = $('<div>', {class: 'personal-referrer-selected'}).appendTo(root);
    const search = $('<input>', {id: searchId, type: 'search', placeholder: 'Имя или телефон — от 2 символов',
      autocomplete: 'off', 'aria-label': 'Поиск рекомендателя', disabled: true}).appendTo(root);
    const status = $('<div>', {class: 'personal-referrer-status', role: 'status', 'aria-live': 'polite'}).appendTo(root);
    const list = $('<ul>', {class: 'personal-referrer-results', 'aria-label': 'Найденные контакты'}).appendTo(root);
    const more = $('<button>', {type: 'button', text: 'Показать ещё', class: 'personal-referrer-more'}).hide().appendTo(root);
    const refresh = $('<button>', {type: 'button', text: 'Обновить', class: 'personal-referrer-refresh'}).appendTo(root);
    const s = {root, api: createReferrerApi(options => $.ajax(options)), dead: false, seq: 0,
      schema: null, card: null, record: null, busy: false, loading: true, query: '', page: 1, timer: null};
    state = s;
    const alive = () => !s.dead && (!s.card || s.card.current());
    const say = text => { if (alive()) status.text(text); };
    function nativeMatches(record) {
      const saved = core.savedId(record, s.schema.referrer.id);
      if (s.card.raw() !== (saved === null ? '' : String(saved))) return false;
      if (s.schema.channel) {
        const entry = (record.custom_fields_values || []).find(f => f.field_id === s.schema.channel.id);
        const val = entry && entry.values && entry.values[0];
        const stored = val && val.enum_id ? String(val.enum_id) : '';
        const live = s.card.raw(s.schema.channel.id);
        if ((live === '0' ? '' : live) !== stored) return false;
      }
      return true;
    }
    function enabled() {
      return alive() && s.record && s.schema && !s.busy && !s.loading &&
        core.eligible(s.record, s.schema) && nativeMatches(s.record);
    }
    function controls() {
      if (!alive()) return;
      let active = false;
      try { active = enabled(); } catch (error) { say(core.errorMessage(error)); }
      search.prop('disabled', !active);
      list.find('button').prop('disabled', !active);
      more.prop('disabled', !active);
      refresh.prop('disabled', s.busy || s.loading);
    }
    s.onChange = () => {
      if (s.syncing || !s.schema || !s.record || !alive()) return;
      s.seq++;
      clearTimeout(s.timer);
      list.empty(); more.hide();
      try {
        if (!nativeMatches(s.record)) say('Сохраните изменения полей карточки, затем нажмите «Обновить».');
      } catch (error) { say(core.errorMessage(error)); }
      controls();
    };
    function showContact(contact) {
      selected.empty().append($('<a>', {href: '/contacts/detail/' + core.id(contact.id), target: '_blank',
        rel: 'noopener noreferrer', text: contact.name || 'Контакт #' + contact.id}));
    }
    async function load() {
      if (s.busy || !alive()) return;
      const seq = ++s.seq;
      clearTimeout(s.timer);
      s.loading = true;
      search.prop('disabled', true); refresh.prop('disabled', true);
      list.empty(); more.hide(); selected.empty(); say('Загрузка…');
      try {
        if (!s.schema) s.schema = core.resolve(await s.api.fields(), self.get_settings());
        if (!alive() || seq !== s.seq) return;
        if (!s.card) {
          s.card = createReferrerCard($, app, s.schema.referrer.id);
          if (!core.id(s.card.id)) throw new Error('Сначала сохраните новую сделку, затем откройте её снова.');
          s.card.onChange(s.onChange);
        }
        const record = await s.api.request('GET', '/api/v4/leads/' + s.card.id);
        if (!alive() || seq !== s.seq) return;
        s.record = record;
        const contactId = core.savedId(record, s.schema.referrer.id);
        if (contactId) {
          try {
            const contact = await s.api.request('GET', '/api/v4/contacts/' + contactId);
            if (!alive() || seq !== s.seq) return;
            if (core.id(contact.id) !== contactId) throw new Error('Контакт не подтверждён.');
            showContact(contact);
          } catch (error) {
            if (!alive() || seq !== s.seq) return;
            selected.text('Contact ID ' + contactId + ': ' + core.errorMessage(error));
          }
        } else selected.text('Рекомендатель не выбран');
        if (!nativeMatches(record)) say('Сохраните изменения полей карточки, затем нажмите «Обновить».');
        else if (!core.eligible(record, s.schema)) say('Выбор доступен для канала «' + s.schema.referral.value + '».');
        else say('Выберите существующий контакт. Выбор сохраняется сразу.');
      } catch (error) { say(core.errorMessage(error)); }
      finally { s.loading = false; controls(); }
    }
    async function choose(contactId, seq) {
      try { if (seq !== s.seq || !enabled()) return; } catch (error) { say(core.errorMessage(error)); return; }
      seq = ++s.seq;
      clearTimeout(s.timer);
      s.busy = true; controls(); say('Проверка и сохранение…');
      let attempted = false;
      try {
        const fresh = await s.api.request('GET', '/api/v4/leads/' + s.card.id);
        if (!alive() || seq !== s.seq) throw new Error('Карточка изменилась. Обновите виджет.');
        if (!core.eligible(fresh, s.schema) || !nativeMatches(fresh)) {
          throw new Error('Канал или рекомендатель изменились. Обновите карточку перед выбором.');
        }
        const contact = await s.api.request('GET', '/api/v4/contacts/' + contactId);
        if (core.id(contact.id) !== contactId) throw new Error('Контакт не подтверждён.');
        if (!alive() || seq !== s.seq || !nativeMatches(fresh)) throw new Error('Карточка изменилась. Обновите виджет.');
        const previous = s.card.raw();
        if (core.savedId(fresh, s.schema.referrer.id) !== contactId) {
          // Recheck immediately before sending a queued mutation; no other lead fields are sent.
          await s.api.request('PATCH', '/api/v4/leads', core.payload(s.card.id, contactId, s.schema), () => {
            if (!alive() || seq !== s.seq || !nativeMatches(fresh)) return false;
            attempted = true;
            return true;
          });
        }
        const verified = await s.api.request('GET', '/api/v4/leads/' + s.card.id);
        if (core.savedId(verified, s.schema.referrer.id) !== contactId) throw new Error('Сохранение не подтверждено. Обновите карточку.');
        if (!alive()) return;
        s.syncing = true;
        let synced;
        try { synced = s.card.sync(previous, contactId); } finally { s.syncing = false; }
        s.record = verified;
        showContact(contact);
        list.empty(); more.hide(); search.val(''); ++s.seq;
        say(synced ? 'Рекомендатель сохранён.' : 'ID сохранён на сервере. Обновите карточку перед дальнейшим редактированием.');
      } catch (error) {
        say((attempted ? 'Результат записи требует проверки. Нажмите «Обновить». ' : '') + core.errorMessage(error));
      } finally { s.busy = false; controls(); }
    }
    async function find(query, page, seq) {
      if (!alive() || seq !== s.seq) return;
      more.hide(); say('Поиск…');
      try {
        const data = await s.api.request('GET', '/api/v4/contacts?query=' + encodeURIComponent(query) + '&limit=10&page=' + page,
          null, () => alive() && seq === s.seq);
        if (!alive() || seq !== s.seq) return;
        const contacts = (data._embedded || {}).contacts || [];
        if (page === 1) list.empty();
        for (const contact of contacts) {
          const contactId = core.id(contact.id);
          if (!contactId) continue;
          const row = $('<li>').appendTo(list);
          const button = $('<button>', {type: 'button', class: 'personal-referrer-option'}).appendTo(row);
          $('<strong>').text(contact.name || 'Контакт #' + contactId).appendTo(button);
          const details = $('<span>').text([core.phone(contact), 'ID ' + contactId].filter(Boolean).join(' · ')).appendTo(button);
          button.on('click.referrer', () => choose(contactId, seq));
          const company = ((contact._embedded || {}).companies || [])[0];
          if (company) {
            // Resolve sequentially, without an uncontrolled burst of requests per result page.
            const name = await s.api.companyName(company).catch(() => 'Компания недоступна');
            if (!alive() || seq !== s.seq) return;
            details.text([name, core.phone(contact), 'ID ' + contactId].filter(Boolean).join(' · '));
          }
        }
        s.page = page;
        more.toggle(!!(data._links || {}).next);
        say(contacts.length ? 'Выберите контакт из списка.' : page === 1 ? 'Контакты не найдены. Новый контакт не создаётся.' : 'Больше контактов нет.');
        controls();
      } catch (error) { if (alive() && seq === s.seq) say(core.errorMessage(error)); }
    }
    search.on('input.referrer', () => {
      const seq = ++s.seq;
      clearTimeout(s.timer); list.empty(); more.hide();
      const query = String(search.val()).trim(); s.query = query;
      if (Array.from(query).length < 2) { say('Введите минимум 2 символа.'); return; }
      s.timer = setTimeout(() => find(query, 1, seq), 450);
    }).on('keydown.referrer', event => {
      if (event.key === 'Escape') { ++s.seq; clearTimeout(s.timer); list.empty(); more.hide(); }
      if (event.key === 'Enter') event.preventDefault();
    });
    more.on('click.referrer', () => find(s.query, s.page + 1, s.seq));
    refresh.on('click.referrer', load);
    load();
    return true;
  }
  this.callbacks = {render: mount, init: () => true, bind_actions: () => true,
    settings: () => true, onSave: () => true, destroy};
  return this;
}

return ReferrerWidget;
});
